# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/new-rd-angular-docs

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
      - store_artifacts:
          path: dist/reports/coverage
      - store_artifacts:
          path: dist/reports/junit
      - store_test_results:
          path: dist/reports/junit

    #   - deploy:
    #       name: ./tools/deploy.sh
    #       command: |
    #         if [ "${CIRCLE_BRANCH}" == "master" ]; then
    #           npm run build-themes
    #           npx ng build --aot --prod
    #           cd functions && yarn install && yarn build
    #           ./tools/deploy.sh
    #         fi

  deploy-job:
    docker:
        - image: circleci/node:8-browsers
    steps:
        - checkout
        - run: npm install
        - run: npm run build
        - run: cd functions && npm install && npm run build
        - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2

  -test_and_deploy:
    jobs:
      - test-job
      - deploy-job:
        requires:
          - test-job
        filters:
          branches:
            only: master